Web/ConformityCheck.Web/Controllers/ConformitiesController.cs
namespace ConformityCheck.Web.Controllers
{
    using System;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;

    using ConformityCheck.Common;
    using ConformityCheck.Data.Models;
    using ConformityCheck.Services.Data;
    using ConformityCheck.Services.Messaging;
    using ConformityCheck.Web.ViewModels;
    using ConformityCheck.Web.ViewModels.Articles;
    using ConformityCheck.Web.ViewModels.Conformities;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    // [AutoValidateAntiforgeryToken] - it is globaly as a service and is in the DC.
    public class ConformitiesController : BaseController
    {
        private const string ArticlesCallerViewName = GlobalConstants.Articles;
        private const string SuppliersCallerViewName = GlobalConstants.Suppliers;
        private const string ConformitiesCallerViewName = GlobalConstants.Conformities;
        private readonly string conformityFilesDirectory;
        private readonly IArticlesService articlesService;
        private readonly ISuppliersService suppliersService;
        private readonly IProductsService productsService;
        private readonly IConformityTypesService conformityTypesService;
        private readonly ISubstancesService substancesService;
        private readonly IConformitiesService conformitiesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;
        private readonly IEmailSender emailSender;
        private readonly ILogger<ConformitiesController> logger;

        public ConformitiesController(
            IArticlesService articlesService,
            ISuppliersService suppliersService,
            IProductsService productsService,
            IConformityTypesService conformityTypesService,
            ISubstancesService substancesService,
            IConformitiesService conformitiesService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment,
            IEmailSender emailSender,
            ILogger<ConformitiesController> logger)
        {
            this.articlesService = articlesService;
            this.suppliersService = suppliersService;
            this.productsService = productsService;
            this.conformityTypesService = conformityTypesService;
            this.substancesService = substancesService;
            this.conformitiesService = conformitiesService;
            this.userManager = userManager;
            this.environment = environment;
            this.emailSender = emailSender;
            this.logger = logger;
            this.conformityFilesDirectory = $"{this.environment.WebRootPath}/files";
        }

        public async Task<IActionResult> Index(PagingViewModel input)
        {
            if (input.PageNumber <= 0)
            {
                // loads StatusCodeError404.cshtm
                return this.NotFound();
            }

            var model = new ConformitiesIndexModel
            {
                ItemsPerPage = input.ItemsPerPage,
                PageNumber = input.PageNumber,
                PagingControllerActionCallName = nameof(this.Index),
                CurrentSortOrder = input.CurrentSortOrder,
                CurrentSearchInput = input.CurrentSearchInput,
                CurrentSortDirection = input.CurrentSortDirection == GlobalConstants.CurrentSortDirectionDesc ?
                             GlobalConstants.CurrentSortDirectionAsc : GlobalConstants.CurrentSortDirectionDesc,
            };

            try
            {
                if (string.IsNullOrWhiteSpace(input.CurrentSearchInput))
                {
                    model.ItemsCount = this.conformitiesService.GetCount();
                    model.Conformities = await this.conformitiesService
                                                .GetAllOrderedAsPagesAsync<ConformityExportModel>(
                                                    input.CurrentSortOrder,
                                                    input.PageNumber,
                                                    input.ItemsPerPage);
                }
                else
                {
                    input.CurrentSearchInput = input.CurrentSearchInput.Trim();
                    model.ItemsCount = this.conformitiesService.GetCountBySearchInput(input.CurrentSearchInput);
                    model.Conformities = await this.conformitiesService
                                                .GetAllBySearchInputOrderedAsPagesAsync<ConformityExportModel>(
                                                    input.CurrentSearchInput,
                                                    input.CurrentSortOrder,
                                                    input.PageNumber,
                                                    input.ItemsPerPage);
                }

                this.logger.LogInformation($"Conformities loaded successfully");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Conformities loading failed: {ex}");

                return this.Redirect("/");
            }

            return this.View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        // [ValidateAntiforgeryToken] - it is globaly as a service
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(ConformityCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.ValidForSingleArticle = false;

                return this.View();
            }

            // TODO - add just supplier's conformity - not connected with articles but a general one.
            try
            {
                // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await this.userManager.GetUserAsync(this.User);
                await this.conformitiesService.CreateAsync(input, user.Id, this.conformityFilesDirectory);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ConformityCreatedSuccessfullyMessage;
                this.logger.LogInformation($"Conformity for article: {input.ArticleId}, conformity type: {input.ConformityTypeId} and supplier: {input.SupplierId} was created by user: {user.Id}");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Conformity creation failed: {ex}");

                // return user to the Create view instead of Home/Error page
                return this.View();
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        [Authorize]
        public async Task<IActionResult> AddToArticleConformityType(ArticleIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

                return this.RedirectToAction(nameof(this.Index), ArticlesCallerViewName);
            }

            // if error accure here, the Home/Error page will be displayed
            var model = await this.articlesService.GetByIdAsync<ArticleManageConformitiesExportModel>(input.Id);

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddToArticleConformityType(ArticleManageConformitiesInputModel input)
        {
            var id = input.Conformity.ArticleId;

            if (!this.ModelState.IsValid)
            {
                var model = await this.articlesService.GetByIdAsync<ArticleManageConformitiesExportModel>(id);

                return this.View(model);
            }

            try
            {
                // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await this.userManager.GetUserAsync(this.User);
                await this.conformitiesService.CreateAsync(input.Conformity, user.Id, this.conformityFilesDirectory);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ConformityCreatedSuccessfullyMessage;
                this.logger.LogInformation($"Conformity for article: {input.Conformity.ArticleId}, conformity type: {input.Conformity.ConformityTypeId} and supplier: {input.Conformity.SupplierId} was created by user: {user.Id}");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogInformation($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Conformity creation failed: {ex}");

                var model = await this.articlesService.GetByIdAsync<ArticleManageConformitiesExportModel>(id);

                return this.View(model);
            }

            return this.RedirectToAction(nameof(ArticlesController.Details), ArticlesCallerViewName, new { id });
        }

        [Authorize]
        public async Task<IActionResult> AddToArticleSupplierConformityType(ConformityGetInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

Web/ConformityCheck.Web/ViewComponents/ConformityTypesViewComponent.cs
namespace ConformityCheck.Web.ViewComponents
{
    using System.Threading.Tasks;

    using ConformityCheck.Services.Data;
    using ConformityCheck.Web.ViewModels.ConformityTypes.ViewComponents;
    using Microsoft.AspNetCore.Mvc;

    public class ConformityTypesViewComponent : ViewComponent
    {
        private readonly IContentDeliveryService contentDeliveryService;

        public ConformityTypesViewComponent(IContentDeliveryService contentDeliveryService)
        {
            this.contentDeliveryService = contentDeliveryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = await this.contentDeliveryService.GetAllConformityTypesAsync<ConformityTypesViewComponentModel>();

            // the default view for this view components is called - this is the Default.cshtml!
            // Another View could be called, just put the name here, but IMPORTANT - do not forget to put this new view in the same
            // folder, that already contains the Default.cshtml view for this View component! This is the folder for this View component
            // views: ...\ConformityCheck\Web\ConformityCheck.Web\Views\Shared\Components\ConformityTypes\Default.cshtml
            // return this.View("Shared", viewModel);
            return this.View(viewModel);
        }
    }
}

Web/ConformityCheck.Web/ViewComponents/SuppliersViewComponent.cs
namespace ConformityCheck.Web.ViewComponents
{
    using System.Threading.Tasks;

    using ConformityCheck.Services.Data;
    using ConformityCheck.Web.ViewModels.Suppliers.ViewComponents;
    using Microsoft.AspNetCore.Mvc;

    [ViewComponent(Name = "Suppliers")]
    public class SuppliersViewComponent : ViewComponent
    {
        private readonly IContentDeliveryService contentDeliveryService;

        public SuppliersViewComponent(IContentDeliveryService contentDeliveryService)
        {
            this.contentDeliveryService = contentDeliveryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = await this.contentDeliveryService.GetAllSuppliersAsync<SuppliersViewComponentModel>();

            // the default view for this view components is called - this is the Default.cshtml!
            // Another View could be called, just put the name here, but IMPORTANT - do not forget to put this new view in the same
            // folder, that already contains the Default.cshtml view for this View component! This is the folder for this View component
            // views: ...\ConformityCheck\Web\ConformityCheck.Web\Views\Shared\Components\Suppliers\Default.cshtml
            // return this.View("Shared", viewModel);
            return this.View(viewModel);
        }
    }
}

Web/ConformityCheck.Web/Views/Conformities/AddToArticleConformityType.cshtml
@model ArticleManageConformitiesExportModel
@{
    this.ViewData["Title"] = "Add conformity to article";
    //var suppliers = Model.SuppliersAvailable.Select(x => new SelectListItem(x.NumberAndName, x.Id));
    //var conformityTypes = Model.ConformityTypesAvailable.Select(x => new SelectListItem(x.Description, x.Id.ToString()));
    //var products = Model.ProductsAvailable.Select(x => new SelectListItem(x.Number, x.Id));
    //var substances = Model.SubstancesAvailable.Select(x => new SelectListItem($"{x.CASNumber} - {x.Description}", x.Id.ToString()));
}


@section SubMenu{
    <partial name="_SubMenuEdit" model="Model" />
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container">
                <article class="data-container article-edit">
                    <ul>
                        <li>
                            Article number:
                            <strong>@Model.Number</strong>
                        </li>
                        <li>
                            Article's description:
                            <strong>@Model.Description</strong>
                        </li>
                    </ul>
                </article>

                <form method="post" class="input-group" asp-controller="Conformities" asp-action="AddToArticleConformityType"
                      enctype="multipart/form-data">

                    <div asp-validation-summary="All" class="text-danger"></div>

                    <input asp-for="Id" hidden value="@Model.Id" />
                    <input asp-for="Conformity.ArticleId" hidden value="@Model.Id" />
                    <input asp-for="Conformity.ValidForSingleArticle" value="true" checked hidden />

                    <div class="SupplierId form-field-container large-margin-vertical">
                        <label asp-for="Conformity.SupplierId">
                           * Select supplier
                        </label>
                        @* ASP.NET gave id="Conformity_SupplierId" to the below select *@
                        <select asp-for="Conformity.SupplierId" class="form-control"></select>
                        <span asp-validation-for="Conformity.SupplierId" class="text-danger"></span>
                    </div>

                    <div class="ConformityTypeId form-field-container large-margin-vertical">
                        <label asp-for="Conformity.ConformityTypeId">
                           * Select conformity type
                        </label>
                        @* ASP.NET gave id="Conformity_ConformityTypeId" to the below select *@
                        <select asp-for="Conformity.ConformityTypeId" class="form-control"></select>
                        <span asp-validation-for="Conformity.ConformityTypeId" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Conformity.IssueDate"></label>
                        <input asp-for="Conformity.IssueDate" class="form-control" placeholder="Date of conformity creation" />
                        <span asp-validation-for="Conformity.IssueDate" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Conformity.ValidityDate"></label>
                        <input asp-for="Conformity.ValidityDate" class="form-control" placeholder="Date till the conformity is valid" />
                        <span asp-validation-for="Conformity.ValidityDate" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Conformity.Comments"></label>
                        <input asp-for="Conformity.Comments" class="form-control" placeholder="Add comments to the conformity" />
                        <span asp-validation-for="Conformity.Comments" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical custom-file-upload-container">
                        <label asp-for="Conformity.InputFile" class="custom-file-upload form-control">
                            <i class="fas fa-file-upload"></i> Choose conformity file
                        </label>
                        <input asp-for="Conformity.InputFile" class="form-control" placeholder="Add file" />
                        <span asp-validation-for="Conformity.InputFile" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Conformity.IsAccepted">
                            If the conformity is accepted, please check this box:
                        </label>
                        <input asp-for="Conformity.IsAccepted" type="checkbox" />
                        <span asp-validation-for="Conformity.IsAccepted" class="text-danger"></span>
                    </div>

                    @* TODO: add the declared substances and assing the restrictions. *@
                    <div class="btns-container">
                        <div class="form-field-container">
                            <a class="btn btn-back btn-align-end"
                               asp-controller="Articles"
                               asp-action="Edit"
                               asp-route-id="@Model.Id">
                                Return back
                            </a>
                        </div>
                        <div class="form-field-container">
                            <input type="submit" class="btn btn-align-end" value="Create" />
                        </div>
                    </div>
                </form>
            </article>
        </section>

        <section class="display-data-footer ">
        </section>
    </section>
</section>

@section Scripts{
    <script src="~/js/suppliersByArticle.js" asp-append-version="true"></script>
}

Web/ConformityCheck.Web/Views/Conformities/Create.cshtml
@model ConformityCreateInputModel
@{
    this.ViewData["Title"] = "Create new conformity";
    //var suppliers = Model.SuppliersAvailable.Select(x => new SelectListItem(x.NumberAndName, x.Id));
    //var conformityTypes = Model.ConformityTypesAvailable.Select(x => new SelectListItem(x.Description, x.Id.ToString()));
    //var products = Model.ProductsAvailable.Select(x => new SelectListItem(x.Number, x.Id));
    //var substances = Model.SubstancesAvailable.Select(x => new SelectListItem($"{x.CASNumber} - {x.Description}", x.Id.ToString()));
}

@section SubMenu{
    <partial name="_SubMenuGeneral" model="Model" />
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container">
                <form method="post" class="input-group" enctype="multipart/form-data">

                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="SupplierId">
                            * Select supplier
                        </label>
                        <cache expires-after="TimeSpan.FromSeconds(120)">
                            <select asp-for="SupplierId" class="form-control">
                                <vc:suppliers></vc:suppliers>
                            </select>
                        </cache>
                        <span asp-validation-for="SupplierId" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="ConformityTypeId">
                            * Select conformity type
                        </label>
                        <cache expires-after="TimeSpan.FromSeconds(1200)">
                            <select asp-for="ConformityTypeId" class="form-control" autofocus>
                                <vc:conformity-types></vc:conformity-types>
                            </select>
                        </cache>
                        <span asp-validation-for="ConformityTypeId" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <p>
                            <strong>
                                * Please select one of the options below. The choosen conformity type will be assigned to the article/s
                                if missing. Available opitions are:
                            </strong>
                        </p>
                        <div class="form-field-container">
                            <article class="form-field-container">
                                <label asp-for="ValidForAllArticles">Conformity for all suppliers' articles:</label>
                                <input asp-for="ValidForAllArticles" type="checkbox">
                            </article>
                            <article class="form-field-container">
                                <label asp-for="ValidForSingleArticle">Conformity for a single article.</label>
                                <input asp-for="ValidForSingleArticle" type="checkbox">
                            </article>
                            <p>
                                (Articles list will be generated if a single article's confirmation is choosen)
                            </p>
                        </div>

                        <div class="articles-container form-field-container" style="display:none">
                            <label asp-for="ArticleId"></label>
                            <select asp-for="ArticleId" class="form-control" autofocus>
                                <option>Select supplier with articles first</option>
                            </select>
                            <span asp-validation-for="ArticleId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="IssueDate"></label>
                        <input asp-for="IssueDate" class="form-control" placeholder="Date of conformity creation" />
                        <span asp-validation-for="IssueDate" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="ValidityDate"></label>
                        <input asp-for="ValidityDate" class="form-control" placeholder="Date till the conformity is valid" />
                        <span asp-validation-for="ValidityDate" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Comments"></label>
                        <input asp-for="Comments" class="form-control" placeholder="Add comments to the conformity" />
                        <span asp-validation-for="Comments" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical custom-file-upload-container">
                        <label asp-for="InputFile" class="custom-file-upload form-control">
                            * <i class="fas fa-file-upload"></i> Choose conformity file
                        </label>
                        <input asp-for="InputFile" class="form-control" placeholder="Add file" />
                        <span asp-validation-for="InputFile" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="IsAccepted">
                            If the conformity is accepted, please check this box:
                        </label>
                        <input asp-for="IsAccepted" type="checkbox" />
                        <span asp-validation-for="IsAccepted" class="text-danger"></span>
                    </div>

                    <div class="btns-container">
                        <div class="form-field-container">
                            <a asp-action="Index" class="btn btn-back btn-align-end">Return back</a>
                        </div>
                        <div class="form-field-container">
                            <input type="reset" class="btn btn-clear btn-align-end" value="Clear form" />
                        </div>
                        <div class="form-field-container">
                            <input type="submit" class="btn btn-align-end" value="Create" />
                        </div>
                    </div>
                </form>
            </article>
        </section>

        <section class="display-data-footer ">
        </section>
    </section>
</section>

@section Scripts{
    <script src="~/js/articlesBySupplier.js" asp-append-version="true"></script>
}

Web/ConformityCheck.Web/Views/Conformities/Index.cshtml
@model ConformitiesIndexModel

@{
    this.ViewData["Title"] = "Conformities";
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
                <span class="presented-items-info">(total of @Model.ItemsCount conformities)</span>
            </article>
            <article class="tools-container">
                <article class="search-container">
                    <form method="get" asp-action="Index" class="flex-row">
                        <article class="input-group">
                            <input type="search" class="form-control" size="40"
                                   asp-for="CurrentSearchInput"
                                   id="searchConformityInput" list="selectSearchConformityInput"
                                   placeholder="Search for article, supplier or conformity type"
                                   value="@Model.CurrentSearchInput"
                                   autocomplete="off">
                            <datalist id="selectSearchConformityInput" class="form-control dropdown-content">
                            </datalist>
                        </article>
                        <article class="btns-container">
                            <button type="submit" class="btn btn-search">
                                <i class="fas fa-search"></i> Search
                            </button>
                        </article>
                    </form>
                </article>
                <article class="input-group">
                    <article class="input-group-prepend">
                        <span class="input-group-text">
                            Items per page
                        </span>
                    </article>
                    <article class="input-group-append">
                        <partial name="_ItemsPerPagePartial" model="Model" />
                    </article>
                </article>
            </article>
        </section>

        <section class="display-data-body">
            <article class="pagination-container">
                <partial name="_PagingPartial" model="@Model" />
            </article>
            <partial name="_ConformitiesIndexTable.cshtml" model="@Model" />
        </section>

        <section class="display-data-footer ">
            <article class="pagination-container">
                <partial name="_PagingPartial" model="@Model" />
            </article>
        </section>
    </section>
</section>

@section SubMenu{
    <partial name="_SubMenuGeneral" />
}

@section Links{
    @*<link href="~/lib/datatables/dist/css/datatables.min.css" rel="stylesheet" asp-append-version="true" />
        @*<link href="~/lib/datatables/DataTables-1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />*@
}

@section Scripts{
    <script src="~/js/tables.js" asp-append-version="true"></script>
    <script src="~/js/searchEntities.js" asp-append-version="true"></script>
    @*<script src="~/lib/datatables/dist/js/datatables.min.js"></script>*@
}