Web/ConformityCheck.Web/Controllers/ArticlesController.cs
namespace ConformityCheck.Web.Controllers
{
    using System;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using ConformityCheck.Common;
    using ConformityCheck.Data.Models;
    using ConformityCheck.Services.Data;
    using ConformityCheck.Web.ViewModels;
    using ConformityCheck.Web.ViewModels.Articles;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class ArticlesController : BaseController
    {
        private readonly IArticlesService articlesService;
        private readonly ISuppliersService suppliersService;
        private readonly IProductsService productsService;
        private readonly IConformityTypesService conformityTypesService;
        private readonly ISubstancesService substancesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<ArticlesController> logger;

        public ArticlesController(
            IArticlesService articlesService,
            ISuppliersService suppliersService,
            IProductsService productsService,
            IConformityTypesService conformityTypesService,
            ISubstancesService substancesService,
            UserManager<ApplicationUser> userManager,
            ILogger<ArticlesController> logger)
        {
            this.articlesService = articlesService;
            this.suppliersService = suppliersService;
            this.productsService = productsService;
            this.conformityTypesService = conformityTypesService;
            this.substancesService = substancesService;
            this.userManager = userManager;
            this.logger = logger;
        }

        // NEVER FORGET async-await + Task<IActionResult>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        public async Task<IActionResult> Index(PagingViewModel input)
        {
            if (input.PageNumber <= 0)
            {
                // loads StatusCodeError404.cshtm
                return this.NotFound();
            }

            var model = new ArticlesIndexModel
            {
                ItemsPerPage = input.ItemsPerPage,
                PageNumber = input.PageNumber,
                PagingControllerActionCallName = nameof(this.Index),
                CurrentSortOrder = input.CurrentSortOrder,
                CurrentSearchInput = input.CurrentSearchInput,
                CurrentSortDirection = input.CurrentSortDirection == GlobalConstants.CurrentSortDirectionDesc ?
                                GlobalConstants.CurrentSortDirectionAsc : GlobalConstants.CurrentSortDirectionDesc,
            };

            try
            {
                if (string.IsNullOrWhiteSpace(input.CurrentSearchInput))
                {
                    model.ItemsCount = this.articlesService.GetCount();
                    model.Articles = await this.articlesService
                                                .GetAllOrderedAsPagesAsync<ArticleDetailsExportModel>(
                                                    input.CurrentSortOrder,
                                                    input.PageNumber,
                                                    input.ItemsPerPage);
                }
                else
                {
                    input.CurrentSearchInput = input.CurrentSearchInput.Trim();
                    model.ItemsCount = this.articlesService.GetCountBySearchInput(input.CurrentSearchInput);
                    model.Articles = await this.articlesService
                                                .GetAllBySearchInputOrderedAsPagesAsync<ArticleDetailsExportModel>(
                                                input.CurrentSearchInput,
                                                input.CurrentSortOrder,
                                                input.PageNumber,
                                                input.ItemsPerPage);
                }
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Articles loading failed: {ex}");

                return this.Redirect("/");
            }

            return this.View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ArticleCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await this.userManager.GetUserAsync(this.User);
                await this.articlesService.CreateAsync(input, user.Id);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ArticleCreatedSuccessfullyMessage;
                this.logger.LogInformation($"Article number: {input.Number} was created by user: {user.Id}");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Article creation failed: {ex}");

                // return user to the Create view instead of Home/Error page
                return this.View();
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        [Authorize]
        public async Task<IActionResult> Details(ArticleIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

                return this.RedirectToAction(nameof(this.Index));
            }

            var model = await this.articlesService.GetByIdAsync<ArticleDetailsExportModel>(input.Id);

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> Edit(ArticleIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

                return this.RedirectToAction(nameof(this.Index));
            }

            var model = await this.articlesService.GetByIdAsync<ArticleDetailsExportModel>(input.Id);

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(ArticleEditInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var model = await this.articlesService.GetByIdAsync<ArticleDetailsExportModel>(input.Id);

                return this.View(model);

                //// not needed with the current model
                // var propertyNumber = nameof(input.Number);
                // if (this.ModelState.Keys.Contains(propertyNumber)
                //    && this.ModelState[propertyNumber].AttemptedValue.ToString() == model.Number)
                // {
                //    this.ModelState.Remove(propertyNumber);
                //    return await this.Edit(input);
                // }
                // return this.View(input);
            }

            try
            {
                // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await this.userManager.GetUserAsync(this.User);
                await this.articlesService.EditAsync(input, user.Id);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ArticleEditedSuccessfullyMessage;
                this.logger.LogInformation($"Article: {input.Id} was edited by user: {user.Id}");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Article modification failed: {ex}");

                var model = await this.articlesService.GetByIdAsync<ArticleDetailsExportModel>(input.Id);

                return this.View(model);
            }

            return this.RedirectToAction(nameof(this.Details), new { input.Id });
        }

        [Authorize]
        public async Task<IActionResult> AddSupplier(ArticleIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

                return this.RedirectToAction(nameof(this.Index));
            }

            var model = await this.articlesService.GetByIdAsync<ArticleManageSuppliersExportModel>(input.Id);

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddSupplier(ArticleManageSuppliersInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var model = await this.articlesService.GetByIdAsync<ArticleManageSuppliersExportModel>(input.Id);

                return this.View(model);
            }

            try
            {
                // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await this.userManager.GetUserAsync(this.User);
                await this.articlesService.AddSupplierAsync(input);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ArticleEditedSuccessfullyMessage;

Web/ConformityCheck.Web/Controllers/ContactFormEntriesController.cs
namespace ConformityCheck.Web.Controllers
{
    using System;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using ConformityCheck.Common;
    using ConformityCheck.Data.Models;
    using ConformityCheck.Services.Data;
    using ConformityCheck.Services.Messaging;
    using ConformityCheck.Web.ViewModels.ContactFormEntries;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class ContactFormEntriesController : BaseController
    {
        private const string RedirectedFromContactForm = "RedirectedFromContactForm";

        private readonly IContactFormEntriesService contactFormEntriesService;
        private readonly IEmailSender emailSender;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<ContactFormEntriesController> logger;

        public ContactFormEntriesController(
            IContactFormEntriesService contactFormEntriesService,
            IEmailSender emailSender,
            UserManager<ApplicationUser> userManager,
            ILogger<ContactFormEntriesController> logger)
        {
            this.contactFormEntriesService = contactFormEntriesService;
            this.emailSender = emailSender;
            this.userManager = userManager;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            if (user != null)
            {
                var model = new ContactFormEntryViewModel
                {
                    Name = user.FirstName != null ? $"{user.FirstName} {user.LastName}" : user.UserName,
                    Email = user.Email,
                };

                return this.View(model);
            }

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormEntryViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                var user = await this.userManager.GetUserAsync(this.User);

                // TODO: Extract to IP provider (service)
                var ip = this.HttpContext.Connection.RemoteIpAddress.ToString();
                input.Ip = ip;

                await this.contactFormEntriesService.CreateAsync(input, user?.Id);

                this.logger.LogInformation($"Contact message from {input.Email} created.");
            }
            catch (Exception ex)
            {
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Contact message creation failed: {ex}.");
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
            }

            try
            {
                // send email to site admin
                await this.emailSender.SendEmailAsync(
                    GlobalConstants.SystemEmail,
                    GlobalConstants.SystemName,
                    GlobalConstants.SystemEmail,
                    GlobalConstants.SystemName,
                    $"You have message from {input.Name}",
                    $"Message content: {input.Title} - {input.Content}");

                this.logger.LogInformation($"Send contact message from {input.Email} to site admin.");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Error sending contact message to site admin: {ex}.");
            }

            try
            {
                // send email to contact message sender
                await this.emailSender.SendEmailAsync(
                    GlobalConstants.SystemEmail,
                    GlobalConstants.SystemName,
                    input.Email,
                    input.Name,
                    "Thank you for your message",
                    $"Dear {input.Name},\r\n Thank you for your interest on our site and the message sent!\r\n We will contact you as soon as we review your request.\r\n\r\nKind Regards,\r\nConformity Check Team");

                this.logger.LogInformation($"Send contact message from site admin to {input.Email}.");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Error sending contact message to user: {ex}.");
            }

            this.TempData[RedirectedFromContactForm] = true;

            return this.RedirectToAction(nameof(this.ThankYou));
        }

        public IActionResult ThankYou()
        {
            if (this.TempData[RedirectedFromContactForm] == null)
            {
                // return this.NotFound();
                // return this.RedirectToAction(nameof(HomeController.Index), nameof(HomeController));
                return this.RedirectToAction(nameof(HomeController.Index), "Home");
            }

            return this.View();
        }
    }
}

Web/ConformityCheck.Web/Views/Shared/StatusCodeError400.cshtml
@{
    this.ViewData["Title"] = "Error 404";
}


<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container flex-column">
                <article class="data-container">
                    <p>
                        <strong>
                            This site cannot be found
                        </strong>
                    </p>
                </article>
                <img class="border-radius" src="~/files/errors/404.gif" />
            </article>
        </section>

        <section class="display-data-footer ">
            <a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-info">Back to home page</a>
        </section>
    </section>
</section>

Web/ConformityCheck.Web/Views/Shared/StatusCodeError404.cshtml
@{
    this.ViewData["Title"] = "Error 404";
}


<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container flex-column">
                <article class="data-container">
                    <p>
                        <strong>
                            This site cannot be found
                        </strong>
                    </p>
                </article>
                <img class="border-radius" src="~/files/errors/404.gif" />
            </article>
        </section>

        <section class="display-data-footer ">
            <a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-info">Back to home page</a>
        </section>
    </section>
</section>

Web/ConformityCheck.Web/Views/Shared/_InfoForTheProjectPartial.cshtml
<p class="large-margin-vertical">
    # CSharp_ASP.NET_Core Web Project
</p>
<p class="large-margin-vertical">
    <b>Conformity Check is a project that manages legal conformity requirements for articles, suppliers and products.</b>
</p>
<p class="large-margin-vertical">
    Conformity Check is dedicated to manage legal conformity requirements that different product types must comply with.
</p>
<p>
    In this <b>complicated regulatory world</b>, we have many <b>different product legislations, regulations, country laws and customer requirements that have to be confirmed</b>.
<p>
    <b>The main goal of the project is to act as a document and regulatory management system</b>.
</p>
<p>
    Very common and typical case in the companies that produce <b>single or complex articles/products</b>, is to have <b>
        articles that need
        several different confirmations
    </b>. At the same time, these articles could have more than one supplier and the <b>
        management of the documents provided by each supplier for each article for each specific conformity type
    </b>is a <b>huge burden</b>
    even for the biggest companies in the World.
    In addition to the fact that <b>articles could be delivered for more than one source, we have separate requirements valid for different countries or clients</b>.
</p>
<p>
    This poses the need of a web tool, that could <b>manage the documents, create records, relationships, generate reports, send requests and update the information provided by the suppliers</b>.
    Even in the current state of the art with all available software tools on the market, <b>the need of a system that could do 
    all those things together and be fit to the production specifics 
    of the today’s supply management is still high</b>.
    The <b>companies are facing more and more issues collecting, managing, evaluating and analysing the information</b>, subsequently – <b>delivering 
    this information on request by clients, customs or control authorities around the World</b>.
</p>
<p>
    When we add the <b>inevitable fact that regulations and requirements in all the countries are changing very frequently</b>, that the 
    <b>specific restrictions are different in different countries</b> and the <b>raising awareness in human society for the environmental and people 
    protection needs, laws and requirements</b>, it is <b>absolutely mandatory all companies to be able to manage the conformity topic with a tool that fits exactly to their needs</b>.
</p>
<p class="large-margin-vertical">
    <b>This is why Conformity Check system was created and where it could vastly help!</b>
</p>
<p class="large-margin-vertical">
    <b>Conformity Check is deployed online and could be found here:</b>
    <a href="https://conformitycheck.dotnetweb.net">https://conformitycheck.dotnetweb.net</a>
</p>

Web/ConformityCheck.Web/Views/Shared/_ItemsPerPagePartial.cshtml
@model PagingViewModel
@foreach (var item in new[] { 12, 24, 48, 96 })
{
    if (item == @Model.ItemsPerPage)
    {
        <div class="page-item active" aria-current="page">
            <span class="page-link">
                @item
                <span class="sr-only">(current)</span>
            </span>
        </div>
    }
    else
    {
        <div class="page-item">
            <a class="page-link" asp-action="@Model.PagingControllerActionCallName"
               asp-route-pageNumber="1"
               asp-route-itemsPerPage="@item"
               asp-route-currentSortOrder="@Model.CurrentSortOrder"
               asp-route-currentSearchInput="@Model.CurrentSearchInput">
                @* if I pass here pageNumber the table will stay on the current page, not start from 1 *@
                @item
            </a>
        </div>
    }
}

Web/ConformityCheck.Web/Views/Shared/_Layout.cshtml
@using ConformityCheck.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <!-- Project level custom fonts -->
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    @*<link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">*@

    <!-- Project level custom styles -->
    @*<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />*@
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />

    @await this.RenderSectionAsync("Links", required: false)
</head>
<body>
    <header class="header-wrapper">
        <section class="content-wrapper header-content">
            <article class="site-title">
                <article class="list-item">
                    <a class="" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="logo-img" src="~/img/logo.png" alt="Logo" />
                        <h5 class="logo-text">
                            @GlobalConstants.SystemName
                        </h5>
                    </a>
                </article>
            </article>

            <label class="toggle-nav" for="toggle-nav">
                <i class="fas fa-bars"></i> Menu
            </label>
            <input class="nav-toggler" type="checkbox" name="toggle-nav" id="toggle-nav" />

            <nav class="nav">
                <ul class="nav-list nav-left">
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="Articles" asp-action="Index">Articles</a>
                    </li>
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                    </li>
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="ConformityTypes" asp-action="Index">Conformity types</a>
                    </li>
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="Conformities" asp-action="Index">Conformities</a>
                    </li>
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="ContactFormEntries" asp-action="Index">Contact us</a>
                    </li>
                    <li class="list-item">
                        <a class="" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                    {
                        <li class="list-item">
                            <a class="" asp-area="Administration" asp-controller="Home" asp-action="Index" title="Admin">Admin</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </nav>
        </section>
    </header>

    <main class="main-wrapper">
        <partial name="_CookieConsentPartial" />
        <section class="content-wrapper">
            <section class="submenu">
                @await RenderSectionAsync("SubMenu", required: false)
            </section>
            <partial name="_MessageViewPartial" />
            @this.RenderBody()
        </section>
    </main>

    <footer class="footer-wrapper">
        <section class="footer-content content-wrapper">
            <ul class="footer-content-social">
                <li class="list-item">
                    <a href="https://www.linkedin.com/in/dyulgerska-paulina-28271583">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </li>
                <li class="list-item">
                    <a href="https://www.facebook.com/paulina.dyulgerska">
                        <i class="fab fa-facebook"></i>
                    </a>
                </li>
                <li class="list-item">
                    <a href="https://www.twitter.com/DyulgerskaP">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
            </ul>
            <p class="footer-made-by">
                Made with love by
                <a class="" asp-area="" asp-controller="Home" asp-action="Index">
                    &nbsp;Paulina
                </a>
            </p>
            <p class="footer-copyright">
                &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - All Rights Reserved
            </p>
            <p class="repo">
                GitHub Repository:&nbsp;<a href="https://github.com/Paulina-Dyulgerska/CSharp_ASP.NET_Core">
                    https://github.com/Paulina-Dyulgerska/CSharp_ASP.NET_Core
                </a>
            </p>
        </section>

    </footer>

    <!-- Project level plugins -->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>*@

    <!-- Project level custom scripts -->
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/alerts.js" asp-append-version="true"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/ConformityCheck.Web/Views/Shared/_MessageViewPartial.cshtml
@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-success" role="alert">
        @this.TempData["Message"]
    </div>
}

@if (this.TempData.ContainsKey("ErrorMessage"))
{
    <div class="alert alert-danger" role="alert">
        @this.TempData["ErrorMessage"]
    </div>
}

Web/ConformityCheck.Web/Views/Shared/_SubMenuEdit.cshtml
<nav>
    <ul class="nav-list">
        <li class="submenu-list-item">
            <span class="btn btn-cta icon-down">Suppliers</span>
            <ul class="quick-nav-submenu">
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="AddSupplier" asp-route-id="@Model.Id">
                        Add Supplier
                    </a>
                </li>
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="ChangeMainSupplier" asp-route-id="@Model.Id">
                        Main Supplier
                    </a>
                </li>
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="RemoveSupplier" asp-route-id="@Model.Id">
                        Remove Supplier
                    </a>
                </li>
            </ul>
        </li>
        <li class="submenu-list-item">
            <span class="btn btn-cta icon-down">Conformity types</span>
            <ul class="quick-nav-submenu">
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="AddConformityType" asp-route-id="@Model.Id">
                        Add conformity type
                    </a>
                </li>
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="RemoveConformityType" asp-route-id="@Model.Id">
                        Remove conformity type
                    </a>
                </li>
            </ul>
        </li>
        <li class="submenu-list-item">
            <span class="btn btn-cta icon-down">Conformities</span>
            <ul class="quick-nav-submenu">
                <li class="list-item">
                    <a class="" asp-controller="Conformities" asp-action="AddToArticleConformityType" asp-route-id="@Model.Id">
                        Add conformity
                    </a>
                </li>
                <li class="list-item">
                    <a class="" asp-controller="Articles" asp-action="RemoveConformity" asp-route-id="@Model.Id">
                        Remove conformity
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>

Web/ConformityCheck.Web/Views/Shared/_SubMenuGeneral.cshtml
<nav>
    <ul class="btns-container nav-list">
        @if (this.User.Identity.IsAuthenticated)
        {
            <li>
                <a asp-controller="Articles" asp-action="Create" class="btn btn-cta">
                    @*<i class="fab fa-creative-commons-remix"></i>*@
                    Create article
                </a>
            </li>
            <li>
                <a asp-controller="Suppliers" asp-action="Create" class="btn btn-cta">
                    @*<i class="fab fa-creative-commons-remix"></i>*@
                    Create supplier
                </a>
            </li>
            <li>
                <a asp-controller="ConformityTypes" asp-action="Create" class="btn btn-cta">
                    @*<i class="fab fa-creative-commons-remix"></i>*@
                    Create conformity type
                </a>
            </li>
            <li>
                <a asp-controller="Conformities" asp-action="Create" class="btn btn-cta">
                    @*<i class="fab fa-creative-commons-remix"></i>*@
                    Create conformity
                </a>
            </li>
        }
    </ul>
</nav>