Web/ConformityCheck.Web/Areas/Administration/Controllers/UsersController.cs
namespace ConformityCheck.Web.Areas.Administration.Controllers
{
    using System;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using ConformityCheck.Common;
    using ConformityCheck.Data.Models;
    using ConformityCheck.Services.Data;
    using ConformityCheck.Services.Mapping;
    using ConformityCheck.Web.ViewModels;
    using ConformityCheck.Web.ViewModels.Administration.Users;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;

    public class UsersController : AdministrationController
    {
        private readonly IUsersService usersService;
        private readonly ILogger<UsersController> logger;
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(
            IUsersService usersService,
            ILogger<UsersController> logger,
            UserManager<ApplicationUser> userManager)
        {
            this.usersService = usersService;
            this.logger = logger;
            this.userManager = userManager;
        }

        public IActionResult Index(PagingViewModel input)
        {
            if (input.PageNumber <= 0)
            {
                // loads StatusCodeError404.cshtm
                return this.NotFound();
            }

            var model = new UsersIndexModel
            {
                ItemsPerPage = input.ItemsPerPage,
                PageNumber = input.PageNumber,
                PagingControllerActionCallName = nameof(this.Index),
                CurrentSortOrder = input.CurrentSortOrder,
                CurrentSearchInput = input.CurrentSearchInput,
                CurrentSortDirection = input.CurrentSortDirection == GlobalConstants.CurrentSortDirectionDesc ?
                                    GlobalConstants.CurrentSortDirectionAsc : GlobalConstants.CurrentSortDirectionDesc,
            };

            try
            {
                if (string.IsNullOrWhiteSpace(input.CurrentSearchInput))
                {
                    model.ItemsCount = this.usersService.GetCount();
                    model.Users = this.usersService.GetAllOrderedAsPages(
                                                    input.CurrentSortOrder,
                                                    input.PageNumber,
                                                    input.ItemsPerPage);
                }
                else
                {
                    input.CurrentSearchInput = input.CurrentSearchInput.Trim();
                    model.ItemsCount = this.usersService.GetCountBySearchInput(input.CurrentSearchInput);
                    model.Users = this.usersService.GetAllBySearchInputOrderedAsPages(
                                                input.CurrentSearchInput,
                                                input.CurrentSortOrder,
                                                input.PageNumber,
                                                input.ItemsPerPage);
                }

                this.logger.LogInformation($"Users loaded successfully");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Users loading failed: {ex}");

                return this.Redirect("/");
            }

            return this.View(model);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                var user = await this.userManager.GetUserAsync(this.User);

                await this.usersService.CreateAsync(input);

                this.TempData[GlobalConstants.TempDataMessagePropertyName] = GlobalConstants.ArticleCreatedSuccessfullyMessage;
                this.logger.LogInformation($"User: {input.UserName} was created by user: {user.Id}");
            }
            catch (Exception ex)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.OperationFailed;
                this.logger.LogError($"RequestID: {Activity.Current?.Id ?? this.HttpContext.TraceIdentifier}; Article creation failed: {ex}");

                // return user to the Create view instead of Home/Error page
                return this.View();
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Edit(string id)
        {
            var user = this.usersService.GetById(id);

            return this.View(user);
        }

        public IActionResult Details(UserIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.TempData[GlobalConstants.TempDataErrorMessagePropertyName] = GlobalConstants.InvalidEntityId;

                return this.RedirectToAction(nameof(this.Index));
            }

            var model = this.usersService.GetById(input.Id);

            return this.View(model);
        }
    }
}

Web/ConformityCheck.Web/ViewComponents/RolesViewComponent.cs
namespace ConformityCheck.Web.ViewComponents
{
    using System.Threading.Tasks;

    using ConformityCheck.Services.Data;
    using ConformityCheck.Web.ViewModels.Administration.Roles.ViewComponents;
    using Microsoft.AspNetCore.Mvc;

    public class RolesViewComponent : ViewComponent
    {
        private readonly IContentDeliveryService contentDeliveryService;

        public RolesViewComponent(IContentDeliveryService contentDeliveryService)
        {
            this.contentDeliveryService = contentDeliveryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = await this.contentDeliveryService.GetAllRolesAsync<RolesViewComponentModel>();

            // the default view for this view components is called - this is the Default.cshtml!
            // Another View could be called, just put the name here, but IMPORTANT - do not forget to put this new view in the same
            // folder, that already contains the Default.cshtml view for this View component! This is the folder for this View component
            // views: ...\ConformityCheck\Web\ConformityCheck.Web\Views\Shared\Components\Roles\Default.cshtml
            // return this.View("Shared", viewModel);
            return this.View(viewModel);
        }
    }
}

Web/ConformityCheck.Web/Areas/Administration/Views/Users/Create.cshtml
@using Microsoft.Extensions.Configuration
@using ConformityCheck.Web.Infrastructure.Settings

@inject IConfiguration Configuration
@inject IGetCountsService GetCountsService

@model UserCreateInputModel
@{
    this.ViewData["Title"] = "Create new user";

    var counts = await this.GetCountsService.GetCounts();
}

@section SubMenu{
    @*<partial name="_SubMenuGeneral" model="Model" />*@
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container">
                <form method="post" class="input-group">
                    @*enctype is multipart/form-data if uploading a file, do not forget to change it*@

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" id="RecaptchaValue" name="RecaptchaValue" />

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="UserName"></label>
                        <input type="text" asp-for="UserName" class="form-control" placeholder="Username /valid email address/" autofocus />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Email"></label>
                        <input type="email" asp-for="Email" class="form-control" placeholder="User email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Password"></label>
                        <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="ConfirmedPassword"></label>
                        <input type="password" asp-for="ConfirmedPassword" class="form-control" placeholder="Repeat password" />
                        <span asp-validation-for="ConfirmedPassword" class="text-danger"></span>
                    </div>
                    
                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="FirstName"></label>
                        <input type="text" asp-for="FirstName" class="form-control" placeholder="First name" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="LastName"></label>
                        <input type="text" asp-for="LastName" class="form-control" placeholder="Last name" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="PhoneNumber"></label>
                        <input type="tel" asp-for="PhoneNumber" class="form-control" placeholder="Phone number" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="EmailConfirmed"></label>
                        <input type="checkbox" asp-for="EmailConfirmed" />
                        <span asp-validation-for="EmailConfirmed" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Roles">User roles (you could choose more than one)</label>
                        <cache expires-after="TimeSpan.FromSeconds(120)">
                            <select size="@(counts.Roles)" asp-for="Roles" class="form-control" placeholder="Roles">
                                <vc:roles></vc:roles>
                            </select>
                        </cache>
                        <span asp-validation-for="Roles" class="text-danger"></span>
                    </div>

                    <div class="btns-container">
                        <div class="form-field-container">
                            <a asp-action="Index" class="btn btn-back btn-align-end">Return back</a>
                        </div>
                        <div class="form-field-container">
                            <input type="reset" class="btn btn-clear btn-align-end" value="Clear form" />
                        </div>
                        <div class="form-field-container">
                            <input type="submit" class="btn btn-align-end" value="Create" />
                        </div>
                    </div>
                </form>
            </article>
        </section>

        <section class="display-data-footer ">
        </section>
    </section>
</section>

@{
    IConfiguration recaptchaSettingsSection = this.Configuration.GetSection(ReCaptchaSettings.ReCaptcha);
    var recaptchaSettings = recaptchaSettingsSection.Get<ReCaptchaSettings>();
}

@section Scripts{
    <script src="https://www.google.com/recaptcha/api.js?render=@recaptchaSettings.SiteKey"></script>
    <script>
        grecaptcha.ready(function () {
            grecaptcha.execute('@recaptchaSettings.SiteKey', { action: 'article_create' })
                .then(function (token) {
                    //console.log('Script reCaptcha loaded!');
                    //console.log('token' + token);
                    document.getElementById('RecaptchaValue').value = token;
                })
                .catch(err => {
                    //console.log('Error: ');
                    //console.log(err.description);
                    //console.log(err);
                });
        });
    </script>

    @*<script src="https://www.google.com/recaptcha/api.js?render=@this.Configuration["GoogleReCaptchaV3Settings:SiteKey"]"></script>
        <script>
            grecaptcha.ready(function () {
                grecaptcha.execute('@this.Configuration["GoogleReCaptchaV3Settings:SiteKey"]', { action: 'article_create' })
                    .then(function (token) {
                        console.log('Script reCaptcha loaded!');
                        console.log('token' + token);
                        document.getElementById('RecaptchaValue').value = token;
                    })
                    .catch(err => {
                        console.log('Error: ');
                        console.log(err.description);
                        console.log(err);
                    });
            });
        </script>*@
}

Web/ConformityCheck.Web/Areas/Administration/Views/Users/Details.cshtml
@model UserViewModel
@{
    this.ViewData["Title"] = "Details for user";
}

@section SubMenu{
    @*<partial name="_SubMenuGeneral" model="Model" />*@
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="data-container article-details">
                <ul>
                    <li>
                        Username:
                        <strong>@Model.UserName</strong>
                    </li>
                    <li>
                        User's email:
                        <strong>@Model.Email</strong>
                    </li>
                    <li>
                        Is user email confirmed:
                        <strong>@(Model.EmailConfirmed ? "Yes" : "No")</strong>
                    </li>
                    <li>
                        User full name:
                        <strong>@Model.FullName</strong>
                    </li>
                    <li>
                        User phone number:
                        <strong>@Model.PhoneNumber</strong>
                    </li>
                    <li>
                        Date of user's creation':
                        <strong>@Model.CreatedOn</strong>
                    </li>
                    <li>
                        User roles:
                        <strong>@string.Join(", ", Model.Roles.Select(r=>r.Name).ToList())</strong>
                    </li>
                </ul>
                <article class="large-margin-horizontal large-margin-vertical center">
                    <a asp-action="Edit" class="btn btn-edit" asp-route-id="@Model.Id">
                        <span class="text">Edit user data</span>
                    </a>
                </article>
            </article>
            <div class="btns-container">
                <div class="form-field-container">
                    <a asp-action="Index" class="btn btn-back btn-align-end">Return back</a>
                </div>
            </div>
        </section>

        <section class="display-data-footer ">
        </section>
    </section>
</section>

Web/ConformityCheck.Web/Areas/Administration/Views/Users/Edit.cshtml
@using Microsoft.Extensions.Configuration
@using ConformityCheck.Web.Infrastructure.Settings

@inject IConfiguration Configuration
@inject IGetCountsService GetCountsService

@model UserViewModel
@{
    this.ViewData["Title"] = "Edit user";

    var counts = await this.GetCountsService.GetCounts();
}

@section SubMenu{
    @*<partial name="_SubMenuGeneral" model="Model" />*@
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
            </article>
        </section>

        <section class="display-data-body">
            <article class="form-data-container">
                <article class="data-container">
                    <ul>
                        <li>
                            Username:
                            <strong>@Model.UserName</strong>
                        </li>
                        <li>
                            Email:
                            <strong>@Model.Email</strong>
                        </li>
                        <li>
                            Is user email confirmed:
                            <strong>@(Model.EmailConfirmed ? "Yes" : "No")</strong>
                        </li>
                        <li>
                            User full name:
                            <strong>@Model.FullName</strong>
                        </li>
                        <li>
                            User phone number:
                            <strong>@Model.PhoneNumber</strong>
                        </li>
                        <li>
                            Date of user's creation':
                            <strong>@Model.CreatedOn</strong>
                        </li>
                        <li>
                            User roles:
                            <strong>@string.Join(", ", Model.Roles.Select(r => r.Name).ToList())</strong>
                        </li>
                    </ul>
                </article>
                <form method="post" class="input-group">
                    @*enctype is multipart/form-data if uploading a file, do not forget to change it*@

                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="FirstName"></label>
                        <input type="text" asp-for="FirstName" class="form-control" placeholder="First name" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="LastName"></label>
                        <input type="text" asp-for="LastName" class="form-control" placeholder="Last name" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="PhoneNumber"></label>
                        <input type="tel" asp-for="PhoneNumber" class="form-control" placeholder="Phone number" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="EmailConfirmed"></label>
                        <input type="checkbox" asp-for="EmailConfirmed" />
                        <span asp-validation-for="EmailConfirmed" class="text-danger"></span>
                    </div>

                    <div class="form-field-container large-margin-vertical">
                        <label asp-for="Roles">User roles (you could choose more than one)</label>
                        <cache expires-after="TimeSpan.FromSeconds(120)">
                            <select size="@(counts.Roles)" asp-for="Roles" class="form-control" placeholder="Roles">
                                <vc:roles></vc:roles>
                            </select>
                        </cache>
                        <span asp-validation-for="Roles" class="text-danger"></span>
                    </div>

                    <div class="btns-container">
                        <div class="form-field-container">
                            <a asp-action="Index" class="btn btn-back btn-align-end">Return back</a>
                        </div>
                        <div class="form-field-container">
                            <input type="reset" class="btn btn-clear btn-align-end" value="Clear form" />
                        </div>
                        <div class="form-field-container">
                            <input type="submit" class="btn btn-align-end" value="Create" />
                        </div>
                    </div>
                </form>
            </article>
        </section>

        <section class="display-data-footer ">
        </section>
    </section>
</section>

Web/ConformityCheck.Web/Areas/Administration/Views/Users/Index.cshtml
@model UsersIndexModel

@{
    this.ViewData["Title"] = "Admin -> Users";
}

@section SubMenu{
    @*<partial name="" />*@

    <nav>
        <ul class="btns-container nav-list">
            <li>
                <a asp-area="Administration" asp-controller="Users" asp-action="Create" class="btn btn-cta">
                    Create user
                </a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Roles" asp-action="Create" class="btn btn-cta">
                    Create role
                </a>
            </li>
        </ul>
    </nav>
}

<section class="display-data-wrapper">
    <section class="display-data-container">

        <section class="display-data-header">
            <article class="title-container">
                <h4 class="title">
                    @this.ViewData["Title"]
                </h4>
                <span class="presented-items-info">(total of @Model.Users.Count() users)</span>
            </article>
            <article class="tools-container">
                <article class="search-container">
                    <form method="get" asp-action="Index" class="flex-row">
                        <article class="input-group">
                            <input type="search" class="form-control" size="40"
                                   asp-for="CurrentSearchInput"
                                   id="searchUserInput" list="selectSearchUserInput"
                                   placeholder="Search for username, email or role" value="@Model.CurrentSearchInput"
                                   autocomplete="off" />
                            <datalist id="selectSearchUserInput" class="form-control dropdown-content">
                            </datalist>
                        </article>
                        <article class="btns-container">
                            <button type="submit" class="btn btn-search">
                                <i class="fas fa-search"></i> Search
                            </button>
                        </article>
                    </form>
                </article>
                <article class="input-group">
                    <article class="input-group-prepend">
                        <span class="input-group-text">
                            Items per page
                        </span>
                    </article>
                    <article class="input-group-append">
                        <partial name="_ItemsPerPagePartial" model="Model" />
                    </article>
                </article>
            </article>
        </section>

        <section class="display-data-body">
            <article class="pagination-container">
                <partial name="_PagingPartial" model="@Model" />
            </article>
            <partial name="_UsersIndexTable.cshtml" model="@Model" />
        </section>

        <section class="display-data-footer">
            <article class="pagination-container">
                <partial name="_PagingPartial" model="@Model" />
            </article>
        </section>
    </section>
</section>

@section Links{
}

@section Scripts{
    <script src="~/js/tables.js" asp-append-version="true"></script>
    <script src="~/js/searchEntities.js" asp-append-version="true"></script>
}

Web/ConformityCheck.Web/Areas/Administration/Views/Users/_UsersIndexTable.cshtml
@model UsersIndexModel

<section class="table-container">
    <article class="table-header"></article>
    <table class="table dataTable">
        <thead>
            <tr>
                <th class="col-m">
                    <a asp-action="@Model.PagingControllerActionCallName"
                       asp-route-itemsPerPage="@Model.ItemsPerPage"
                       asp-route-currentSortOrder="@Model.UserNameSortParam"
                       asp-route-currentSearchInput="@Model.CurrentSearchInput"
                       asp-route-currentSortDirection="@Model.CurrentSortDirection">
                        <span class="text">Username</span>
                        <span class="icon @Model.CurrentSortDirection">
                            @*<i class="fas fa-arrows-alt-v"></i>*@
                        </span>
                    </a>
                </th>
                <th class="col-m">
                    <a asp-action="@Model.PagingControllerActionCallName"
                       asp-route-itemsPerPage="@Model.ItemsPerPage"
                       asp-route-currentSortOrder="@Model.UserEmailSortParam"
                       asp-route-currentSearchInput="@Model.CurrentSearchInput"
                       asp-route-currentSortDirection="@Model.CurrentSortDirection">
                        <span class="text">Email</span>
                        <span class="icon @Model.CurrentSortDirection">
                            @*<i class="fas fa-arrows-alt-v"></i>*@
                        </span>
                    </a>
                </th>
                <th class="col-s">
                    <a asp-action="@Model.PagingControllerActionCallName"
                       asp-route-itemsPerPage="@Model.ItemsPerPage"
                       asp-route-currentSortOrder="@Model.UserFullNameSortParam"
                       asp-route-currentSearchInput="@Model.CurrentSearchInput"
                       asp-route-currentSortDirection="@Model.CurrentSortDirection">
                        <span class="text">Full name</span>
                        <span class="icon @Model.CurrentSortDirection">
                            @*<i class="fas fa-arrows-alt-v"></i>*@
                        </span>
                    </a>
                </th>
                <th class="col-s">Phone number</th>
                <th class="col-s">
                    <a asp-action="@Model.PagingControllerActionCallName"
                       asp-route-itemsPerPage="@Model.ItemsPerPage"
                       asp-route-currentSortOrder="@Model.UserRolesSortParam"
                       asp-route-currentSearchInput="@Model.CurrentSearchInput"
                       asp-route-currentSortDirection="@Model.CurrentSortDirection">
                        <span class="text">Roles</span>
                        <span class="icon @Model.CurrentSortDirection">
                            @*<i class="fas fa-arrows-alt-v"></i>*@
                        </span>
                    </a>
                </th>
                <th class="col-s">
                    <a asp-action="@Model.PagingControllerActionCallName"
                       asp-route-itemsPerPage="@Model.ItemsPerPage"
                       asp-route-currentSortOrder="@Model.UserEmailConfirmedSortParam"
                       asp-route-currentSearchInput="@Model.CurrentSearchInput"
                       asp-route-currentSortDirection="@Model.CurrentSortDirection">
                        <span class="text">Email confirmed</span>
                        <span class="icon @Model.CurrentSortDirection">
                            @*<i class="fas fa-arrows-alt-v"></i>*@
                        </span>
                    </a>
                </th>
                <th class="col-s">Details</th>
                <th class="col-s">Edit</th>
                <th class="col-s">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in this.Model.Users)
            {
            <tr class="" data-id="@user.Id">
                <td class="col-m" data-label="Username">@user.UserName</td>
                <td class="col-m" data-label="Email">@user.Email</td>
                <td class="col-s" data-label="Full name">@user.FullName</td>
                <td class="col-s" data-label="Phone number">@user.PhoneNumber</td>
                <td class="col-s" data-label="Roles">@string.Join(", ", user.Roles.Select(r => r.Name))</td>
                <td class="col-s" data-label="Email confirmed">@(user.EmailConfirmed ? "Yes" : "No")</td>
                <td class="col-s" data-label="Details">
                    <a asp-action="Details" class="btn btn-details" asp-route-id="@user.Id">
                        <span class="text">Details</span>
                    </a>
                </td>
                <td class="col-s" data-label="Edit">
                    <a asp-action="Edit" class="btn btn-edit" asp-route-id="@user.Id">
                        <span class="text">Edit</span>
                    </a>
                </td>
                <td class="col-s" data-label="Delete">
                    <a asp-action="Delete" class="btn btn-delete" asp-route-id="@user.Id">
                        <span class="text">Delete</span>
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</section>